services:

  mongodb:
    image: mongo:8.0
    #mongodb/mongodb-community-server:8.0
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
      - ./examples/:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - shared-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_browser
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_PASSWORD}
    depends_on:
      - mongodb
    networks:
      - shared-network
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 8082:3000
    environment:
      MB_DB_TYPE: ${METABASE_DB_TYPE}
      MB_DB_DBNAME: ${METABASE_DB_NAME}
      MB_DB_PORT: ${POSTGRES_PORT}
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: ${POSTGRES_HOST}
    networks:
      - shared-network
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    volumes:
      - /data/postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${METABASE_DB_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge

#volumes:
#   mongodb:
#    driver: local